import type { Memory } from "@/lib/types"
import { MEMORY_TYPE_COLOR } from "@/lib/brain-logic"

/**
 * 23 mock memories spread across 2020–2024 with intentional clusters
 * (multiple memories within ≤7 days) so cronological connections render.
 *
 * Thumbnails use Next.js' /placeholder.svg query API so they render
 * deterministic illustrations without bundling real assets.
 */
export const mockMemories: Memory[] = [
  // ── 2020 ──
  {
    id: "m1",
    type: "photo",
    date: "2020-04-12",
    title: "Primer atardecer en cuarentena",
    tags: ["Hogar", "Reflexión"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    description: "El cielo se tiñó de rosa por encima de los edificios silenciosos.",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m2",
    type: "note",
    date: "2020-04-14",
    title: "Lista de cosas que extraño",
    tags: ["Personal"],
    location: null,
    description: "Abrazos, cafés afuera, el sonido de una calle llena.",
    color: MEMORY_TYPE_COLOR.note,
  },
  {
    id: "m3",
    type: "audio",
    date: "2020-04-18",
    title: "Reflexiones sobre el tiempo",
    tags: ["Voz", "Filosofía"],
    location: null,
    duration: "3:12",
    color: MEMORY_TYPE_COLOR.audio,
  },
  {
    id: "m4",
    type: "video",
    date: "2020-09-03",
    title: "Reencuentro con la familia",
    tags: ["Familia"],
    location: { lat: -31.4, lng: -64.2, name: "Córdoba, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    duration: "1:48",
    color: MEMORY_TYPE_COLOR.video,
  },

  // ── 2021 ──
  {
    id: "m5",
    type: "photo",
    date: "2021-01-15",
    title: "Año nuevo en la costa",
    tags: ["Viajes", "Mar"],
    location: { lat: -38.0, lng: -57.6, name: "Mar del Plata, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m6",
    type: "note",
    date: "2021-01-22",
    title: "Propósitos del año",
    tags: ["Personal"],
    location: null,
    description: "Aprender, viajar, escribir más.",
    color: MEMORY_TYPE_COLOR.note,
  },
  {
    id: "m7",
    type: "audio",
    date: "2021-06-10",
    title: "Conversación con mi abuela",
    tags: ["Familia", "Voz"],
    location: null,
    duration: "8:42",
    color: MEMORY_TYPE_COLOR.audio,
  },
  {
    id: "m8",
    type: "video",
    date: "2021-11-30",
    title: "Cumpleaños sorpresa",
    tags: ["Celebración", "Amigos"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    duration: "2:15",
    color: MEMORY_TYPE_COLOR.video,
  },

  // ── 2022 ──
  {
    id: "m9",
    type: "photo",
    date: "2022-02-08",
    title: "Caminata en el bosque",
    tags: ["Naturaleza"],
    location: { lat: -41.1, lng: -71.3, name: "Bariloche, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m10",
    type: "photo",
    date: "2022-03-12",
    title: "Atardecer en la montaña",
    tags: ["Naturaleza", "Viajes"],
    location: { lat: -33.4, lng: -70.6, name: "Mendoza, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m11",
    type: "audio",
    date: "2022-03-15",
    title: "Nota de voz: reflexiones",
    tags: ["Personal", "Voz"],
    location: null,
    duration: "2:34",
    color: MEMORY_TYPE_COLOR.audio,
  },
  {
    id: "m12",
    type: "photo",
    date: "2022-03-22",
    title: "Senderismo de altura",
    tags: ["Aventura", "Naturaleza"],
    location: { lat: -33.4, lng: -70.6, name: "Mendoza, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m13",
    type: "video",
    date: "2022-08-19",
    title: "Concierto inolvidable",
    tags: ["Música"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    duration: "0:58",
    color: MEMORY_TYPE_COLOR.video,
  },
  {
    id: "m14",
    type: "note",
    date: "2022-12-24",
    title: "Carta a mi yo del futuro",
    tags: ["Personal"],
    location: null,
    description: "Recordá que sobreviviste a 2020. Todo lo demás es ganancia.",
    color: MEMORY_TYPE_COLOR.note,
  },

  // ── 2023 ──
  {
    id: "m15",
    type: "photo",
    date: "2023-05-07",
    title: "Café con amigos",
    tags: ["Amigos"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m16",
    type: "audio",
    date: "2023-05-14",
    title: "Una canción que escribí",
    tags: ["Música", "Creatividad"],
    location: null,
    duration: "3:48",
    color: MEMORY_TYPE_COLOR.audio,
  },
  {
    id: "m17",
    type: "video",
    date: "2023-09-01",
    title: "Primer día en el nuevo trabajo",
    tags: ["Carrera"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    duration: "0:32",
    color: MEMORY_TYPE_COLOR.video,
  },
  {
    id: "m18",
    type: "note",
    date: "2023-09-09",
    title: "Una semana de aprendizajes",
    tags: ["Carrera", "Reflexión"],
    location: null,
    description: "El cambio asusta, pero abre puertas que no sabías que existían.",
    color: MEMORY_TYPE_COLOR.note,
  },

  // ── 2024 ──
  {
    id: "m19",
    type: "photo",
    date: "2024-03-15",
    title: "Atardecer en Mendoza",
    tags: ["Naturaleza", "Viajes"],
    location: { lat: -33.4, lng: -70.6, name: "Mendoza, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m20",
    type: "audio",
    date: "2024-03-18",
    title: "Reflexiones sobre el viaje",
    tags: ["Personal", "Voz"],
    location: null,
    duration: "2:34",
    color: MEMORY_TYPE_COLOR.audio,
  },
  {
    id: "m21",
    type: "photo",
    date: "2024-03-23",
    title: "El último día en la viña",
    tags: ["Viajes", "Gastronomía"],
    location: { lat: -33.4, lng: -70.6, name: "Mendoza, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    color: MEMORY_TYPE_COLOR.photo,
  },
  {
    id: "m22",
    type: "video",
    date: "2024-07-04",
    title: "Festejo en familia",
    tags: ["Familia", "Celebración"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "/placeholder.svg?height=400&width=600",
    duration: "1:22",
    color: MEMORY_TYPE_COLOR.video,
  },
  {
    id: "m23",
    type: "note",
    date: "2024-11-20",
    title: "Gratitud al final del año",
    tags: ["Personal"],
    location: null,
    description: "Tantos comienzos. Tantas personas. Tanto aprendido.",
    color: MEMORY_TYPE_COLOR.note,
  },
]
