import type { MemoryExtended } from "@/lib/types"
import { MEMORY_TYPE_COLOR } from "@/lib/brain-logic"

/**
 * Rich mock memories spanning 1985–2025 with therapeutic tags,
 * family donations, geographic diversity, and intentional clusters
 * (multiple memories within ≤7 days) so chronological connections render.
 */
export const mockMemories: MemoryExtended[] = [
  // ── HITOS DE VIDA (más grandes en modo CLUSTER) ─────────────────────────
  {
    id: "m1",
    type: "photo",
    date: "2003-06-15",
    title: "Mi graduación del secundario",
    tags: ["Logros", "Familia"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    description: "El día que dejé de ser adolescente. Mamá lloraba más que yo.",
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m2",
    type: "photo",
    date: "2010-03-20",
    title: "Primera vez en Buenos Aires",
    tags: ["Viajes", "Personal"],
    location: { lat: -34.61, lng: -58.37, name: "Buenos Aires, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    description: "El obelisco, el subte, la locura. Todo era nuevo.",
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m3",
    type: "audio",
    date: "2018-12-31",
    title: "Mensaje de fin de año para mí del futuro",
    tags: ["Personal", "Reflexión"],
    location: null,
    color: MEMORY_TYPE_COLOR.audio,
    duration: "3:22",
    source: "self",
    therapeuticTag: "identity",
  },

  // ── RECUERDOS FAMILIARES ─────────────────────────────────────────────────
  {
    id: "m4",
    type: "photo",
    date: "2015-01-10",
    title: "Año nuevo en familia — Colón",
    tags: ["Familia", "Amor"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1542044801-44bfb229eb2a?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "family_bond",
  },
  {
    id: "m5",
    type: "video",
    date: "2022-07-04",
    title: "Cumpleaños de 30 — primer brindis",
    tags: ["Amigos", "Celebración"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1530103862676-de3c9da59a9b?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.video,
    duration: "1:22",
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m6",
    type: "audio",
    date: "2024-11-08",
    title: "Llamada con mamá — grabé el final",
    tags: ["Familia", "Amor"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    color: MEMORY_TYPE_COLOR.audio,
    duration: "1:47",
    source: "self",
    therapeuticTag: "family_bond",
  },

  // ── VIAJES ───────────────────────────────────────────────────────────────
  {
    id: "m7",
    type: "photo",
    date: "2019-05-12",
    title: "Primer viaje internacional — Montevideo",
    tags: ["Viajes"],
    location: { lat: -34.9, lng: -56.16, name: "Montevideo, UY" },
    thumbnailUrl: "https://images.unsplash.com/photo-1589136125010-f13c6bfaab5c?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "happy_place",
  },
  {
    id: "m8",
    type: "photo",
    date: "2023-09-20",
    title: "Patagonia — Torres del Paine",
    tags: ["Viajes", "Naturaleza"],
    location: { lat: -51.0, lng: -73.0, name: "Torres del Paine, CL" },
    thumbnailUrl: "https://images.unsplash.com/photo-1490682143684-14369e18dce8?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "happy_place",
  },
  {
    id: "m9",
    type: "photo",
    date: "2022-02-08",
    title: "Caminata en el bosque",
    tags: ["Naturaleza", "Viajes"],
    location: { lat: -41.1, lng: -71.3, name: "Bariloche, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "happy_place",
  },
  {
    id: "m10",
    type: "photo",
    date: "2024-03-15",
    title: "Atardecer en Mendoza",
    tags: ["Naturaleza", "Viajes"],
    location: { lat: -33.4, lng: -70.6, name: "Mendoza, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "sensory",
  },

  // ── RECUERDOS COTIDIANOS Y REFLEXIONES ───────────────────────────────────
  {
    id: "m11",
    type: "note",
    date: "2024-02-14",
    title: "Nota: lo que aprendí este año",
    tags: ["Personal", "Reflexión"],
    location: null,
    color: MEMORY_TYPE_COLOR.note,
    description: "Aprendí a soltar. A abrazar lo que viene sin forzar.",
    source: "self",
    therapeuticTag: "identity",
  },
  {
    id: "m12",
    type: "photo",
    date: "2025-03-01",
    title: "Primera reunión del proyecto Antovel",
    tags: ["Trabajo", "Logros"],
    location: { lat: -34.61, lng: -58.37, name: "Buenos Aires, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "life_milestone",
  },

  // ── CUARENTENA (cluster cercano) ────────────────────────────────────────
  {
    id: "m13",
    type: "photo",
    date: "2020-04-12",
    title: "Primer atardecer en cuarentena",
    tags: ["Hogar", "Reflexión"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?q=80&w=600&auto=format&fit=crop",
    description: "El cielo se tiñó de rosa por encima de los edificios silenciosos.",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "sensory",
  },
  {
    id: "m14",
    type: "note",
    date: "2020-04-14",
    title: "Lista de cosas que extraño",
    tags: ["Personal"],
    location: null,
    description: "Abrazos, cafés afuera, el sonido de una calle llena.",
    color: MEMORY_TYPE_COLOR.note,
    source: "self",
    therapeuticTag: "identity",
  },
  {
    id: "m15",
    type: "audio",
    date: "2020-04-18",
    title: "Reflexiones sobre el tiempo",
    tags: ["Voz", "Filosofía"],
    location: null,
    duration: "3:12",
    color: MEMORY_TYPE_COLOR.audio,
    source: "self",
    therapeuticTag: "daily_anchor",
  },
  {
    id: "m16",
    type: "video",
    date: "2020-09-03",
    title: "Reencuentro con la familia",
    tags: ["Familia"],
    location: { lat: -31.4, lng: -64.2, name: "Córdoba, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=600&auto=format&fit=crop",
    duration: "1:48",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "family_bond",
  },

  // ── SOCIALES ─────────────────────────────────────────────────────────────
  {
    id: "m17",
    type: "audio",
    date: "2021-06-10",
    title: "Conversación con mi abuela",
    tags: ["Familia", "Voz"],
    location: null,
    duration: "8:42",
    color: MEMORY_TYPE_COLOR.audio,
    source: "self",
    therapeuticTag: "family_bond",
  },
  {
    id: "m18",
    type: "video",
    date: "2021-11-30",
    title: "Cumpleaños sorpresa",
    tags: ["Celebración", "Amigos"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1530103862676-de3c9da59a9b?q=80&w=600&auto=format&fit=crop",
    duration: "2:15",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "daily_anchor",
  },

  // ── CREATIVIDAD ──────────────────────────────────────────────────────────
  {
    id: "m19",
    type: "audio",
    date: "2023-05-14",
    title: "Una canción que escribí",
    tags: ["Música", "Creatividad"],
    location: null,
    duration: "3:48",
    color: MEMORY_TYPE_COLOR.audio,
    source: "self",
    therapeuticTag: "sensory",
  },
  {
    id: "m20",
    type: "video",
    date: "2022-08-19",
    title: "Concierto inolvidable",
    tags: ["Música"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=600&auto=format&fit=crop",
    duration: "0:58",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "sensory",
  },

  // ── CARRERA ──────────────────────────────────────────────────────────────
  {
    id: "m21",
    type: "video",
    date: "2023-09-01",
    title: "Primer día en el nuevo trabajo",
    tags: ["Carrera", "Trabajo"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=600&auto=format&fit=crop",
    duration: "0:32",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m22",
    type: "note",
    date: "2023-09-09",
    title: "Una semana de aprendizajes",
    tags: ["Carrera", "Reflexión"],
    location: null,
    description: "El cambio asusta, pero abre puertas que no sabías que existían.",
    color: MEMORY_TYPE_COLOR.note,
    source: "self",
    therapeuticTag: "daily_anchor",
  },

  // ── ALZHEIMER ESSENCE DONATIONS (Injected by family via MCP) ───────────
  {
    id: "m23",
    type: "photo",
    date: "1985-02-14",
    title: "Nuestra luna de miel en Mar del Plata",
    tags: ["Familia", "Amor", "Historia"],
    location: { lat: -38.0, lng: -57.5, name: "Mar del Plata, AR" },
    thumbnailUrl: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?q=80&w=600&auto=format&fit=crop",
    color: MEMORY_TYPE_COLOR.photo,
    description:
      "Teníamos 22 años. Nos escapamos en un tren viejo que tardó 10 horas. Hacía frío pero éramos felices.",
    source: "family",
    therapeuticTag: "identity", // Very important for reminiscence
    isFamilyDonation: true,
    donorName: "Marta",
    donorRelation: "Esposa",
    injectionNote: "Lauti, este recuerdo siempre lo hace sonreír cuando se siente perdido.",
    injectionStatus: "active",
  },
  {
    id: "m24",
    type: "audio",
    date: "1992-07-04",
    title: "Cuando nació Lautaro",
    tags: ["Familia", "Hitos"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    color: MEMORY_TYPE_COLOR.audio,
    duration: "4:15",
    source: "family",
    therapeuticTag: "family_bond",
    isFamilyDonation: true,
    donorName: "Marta",
    donorRelation: "Esposa",
    injectionNote: "Grabación que hice con la videocámara el día que lo trajimos a casa.",
    injectionStatus: "active",
  },
]
