import type { MemoryExtended } from "@/lib/types"
import { MEMORY_TYPE_COLOR } from "@/lib/brain-logic"

const UNSPLASH_IMAGE_BY_ID: Record<string, string> = {
  m1: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=900&q=82",
  m2: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=900&q=82",
  m3: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=82",
  m4: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=900&q=82",
  m5: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=900&q=82",
  m6: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=82",
  m7: "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?auto=format&fit=crop&w=900&q=82",
  m8: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=82",
  m9: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=82",
  m10: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=82",
  m11: "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=82",
  m12: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=82",
  m13: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=900&q=82",
  m14: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=900&q=82",
  m15: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=900&q=82",
  m16: "https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=900&q=82",
  m17: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=82",
  m18: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=900&q=82",
  m19: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=82",
  m20: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=82",
  m21: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=82",
  m22: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=82",
  m23: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=82",
  m24: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?auto=format&fit=crop&w=900&q=82",
}

/**
 * Rich mock memories spanning 1985–2025 with therapeutic tags,
 * family donations, geographic diversity, and intentional clusters
 * (multiple memories within ≤7 days) so chronological connections render.
 */

// ─── Helper para generar URLs de imagen seguras ───────────────────────────
function safeImageUrl(id: string, type: string): string {
  if (UNSPLASH_IMAGE_BY_ID[id]) return UNSPLASH_IMAGE_BY_ID[id]
  const seed = id.split("").reduce((acc, c) => acc + c.charCodeAt(0), 0) % 1000
  const cats: Record<string, string> = {
    photo: `https://picsum.photos/seed/foto${seed}/600/400`,
    video: `https://picsum.photos/seed/vid${seed}/600/400`,
    audio: `https://picsum.photos/seed/aud${seed}/600/400`,
    note: `https://picsum.photos/seed/nota${seed}/600/400`,
  }
  return cats[type] ?? `https://picsum.photos/seed/${seed}/600/400`
}

// ─── Coordenadas de ubicaciones ────────────────────────────────────────────
export const LOCATION_COORDS: Record<string, { lat: number; lng: number }> = {
  "Colón": { lat: -32.22, lng: -58.15 },
  "Paraná": { lat: -31.73, lng: -60.53 },
  "Concordia": { lat: -31.39, lng: -58.02 },
  "Gualeguaychú": { lat: -33.01, lng: -58.52 },
  "Buenos Aires": { lat: -34.60, lng: -58.38 },
  "Mendoza": { lat: -32.89, lng: -68.83 },
  "Córdoba": { lat: -31.42, lng: -64.19 },
  "Mar del Plata": { lat: -38.00, lng: -57.55 },
  "Rosario": { lat: -32.94, lng: -60.65 },
  "Bariloche": { lat: -41.13, lng: -71.31 },
  "Salta": { lat: -24.79, lng: -65.41 },
  "Tucumán": { lat: -26.82, lng: -65.22 },
  "Madrid": { lat: 40.42, lng: -3.70 },
  "Barcelona": { lat: 41.39, lng: 2.17 },
  "Nueva York": { lat: 40.71, lng: -74.01 },
  "Miami": { lat: 25.76, lng: -80.19 },
  "París": { lat: 48.86, lng: 2.35 },
  "Montevideo": { lat: -34.90, lng: -56.16 },
  "Santiago": { lat: -33.45, lng: -70.67 },
  "Torres del Paine": { lat: -51.0, lng: -73.0 },
}

export const mockMemories: MemoryExtended[] = [
  // ── HITOS DE VIDA (más grandes en modo CLUSTER) ─────────────────────────
  {
    id: "m1",
    type: "photo",
    date: "2003-06-15",
    title: "Mi graduación del secundario",
    tags: ["Logros", "Familia"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    lat: -32.22,
    lng: -58.15,
    imageUrl: safeImageUrl("m1", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    description: "El día que dejé de ser adolescente. Mamá lloraba más que yo.",
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m2",
    type: "photo",
    date: "2010-03-20",
    title: "Primera vez en Buenos Aires",
    tags: ["Viajes", "Personal"],
    location: { lat: -34.61, lng: -58.37, name: "Buenos Aires, AR" },
    lat: -34.60,
    lng: -58.38,
    imageUrl: safeImageUrl("m2", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    description: "El obelisco, el subte, la locura. Todo era nuevo.",
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m3",
    type: "audio",
    date: "2018-12-31",
    title: "Mensaje de fin de año para mí del futuro",
    tags: ["Personal", "Reflexión"],
    location: null,
    imageUrl: safeImageUrl("m3", "audio"),
    color: MEMORY_TYPE_COLOR.audio,
    duration: "3:22",
    source: "self",
    therapeuticTag: "identity",
  },

  // ── RECUERDOS FAMILIARES ─────────────────────────────────────────────────
  {
    id: "m4",
    type: "photo",
    date: "2015-01-10",
    title: "Año nuevo en familia — Colón",
    tags: ["Familia", "Amor"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    lat: -32.22,
    lng: -58.15,
    imageUrl: safeImageUrl("m4", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "family_bond",
  },
  {
    id: "m5",
    type: "video",
    date: "2022-07-04",
    title: "Cumpleaños de 30 — primer brindis",
    tags: ["Amigos", "Celebración"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    lat: -32.22,
    lng: -58.15,
    imageUrl: safeImageUrl("m5", "video"),
    color: MEMORY_TYPE_COLOR.video,
    duration: "1:22",
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m6",
    type: "audio",
    date: "2024-11-08",
    title: "Llamada con mamá — grabé el final",
    tags: ["Familia", "Amor"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    lat: -32.22,
    lng: -58.15,
    imageUrl: safeImageUrl("m6", "audio"),
    color: MEMORY_TYPE_COLOR.audio,
    duration: "1:47",
    source: "self",
    therapeuticTag: "family_bond",
  },

  // ── VIAJES ───────────────────────────────────────────────────────────────
  {
    id: "m7",
    type: "photo",
    date: "2019-05-12",
    title: "Primer viaje internacional — Montevideo",
    tags: ["Viajes"],
    location: { lat: -34.9, lng: -56.16, name: "Montevideo, UY" },
    lat: -34.90,
    lng: -56.16,
    imageUrl: safeImageUrl("m7", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "happy_place",
  },
  {
    id: "m8",
    type: "photo",
    date: "2023-09-20",
    title: "Patagonia — Torres del Paine",
    tags: ["Viajes", "Naturaleza"],
    location: { lat: -51.0, lng: -73.0, name: "Torres del Paine, CL" },
    lat: -51.0,
    lng: -73.0,
    imageUrl: safeImageUrl("m8", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "happy_place",
  },
  {
    id: "m9",
    type: "photo",
    date: "2022-02-08",
    title: "Caminata en el bosque",
    tags: ["Naturaleza", "Viajes"],
    location: { lat: -41.1, lng: -71.3, name: "Bariloche, AR" },
    lat: -41.13,
    lng: -71.31,
    imageUrl: safeImageUrl("m9", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "happy_place",
  },
  {
    id: "m10",
    type: "photo",
    date: "2024-03-15",
    title: "Atardecer en Mendoza",
    tags: ["Naturaleza", "Viajes"],
    location: { lat: -33.4, lng: -70.6, name: "Mendoza, AR" },
    lat: -32.89,
    lng: -68.83,
    imageUrl: safeImageUrl("m10", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "sensory",
  },

  // ── RECUERDOS COTIDIANOS Y REFLEXIONES ───────────────────────────────────
  {
    id: "m11",
    type: "note",
    date: "2024-02-14",
    title: "Nota: lo que aprendí este año",
    tags: ["Personal", "Reflexión"],
    location: null,
    imageUrl: safeImageUrl("m11", "note"),
    color: MEMORY_TYPE_COLOR.note,
    description: "Aprendí a soltar. A abrazar lo que viene sin forzar.",
    source: "self",
    therapeuticTag: "identity",
  },
  {
    id: "m12",
    type: "photo",
    date: "2025-03-01",
    title: "Primera reunión del proyecto Antovel",
    tags: ["Trabajo", "Logros"],
    location: { lat: -34.61, lng: -58.37, name: "Buenos Aires, AR" },
    lat: -34.60,
    lng: -58.38,
    imageUrl: safeImageUrl("m12", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "life_milestone",
  },

  // ── CUARENTENA (cluster cercano) ────────────────────────────────────────
  {
    id: "m13",
    type: "photo",
    date: "2020-04-12",
    title: "Primer atardecer en cuarentena",
    tags: ["Hogar", "Reflexión"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    lat: -34.60,
    lng: -58.38,
    imageUrl: safeImageUrl("m13", "photo"),
    description: "El cielo se tiñó de rosa por encima de los edificios silenciosos.",
    color: MEMORY_TYPE_COLOR.photo,
    source: "self",
    therapeuticTag: "sensory",
  },
  {
    id: "m14",
    type: "note",
    date: "2020-04-14",
    title: "Lista de cosas que extraño",
    tags: ["Personal"],
    location: null,
    imageUrl: safeImageUrl("m14", "note"),
    description: "Abrazos, cafés afuera, el sonido de una calle llena.",
    color: MEMORY_TYPE_COLOR.note,
    source: "self",
    therapeuticTag: "identity",
  },
  {
    id: "m15",
    type: "audio",
    date: "2020-04-18",
    title: "Reflexiones sobre el tiempo",
    tags: ["Voz", "Filosofía"],
    location: null,
    imageUrl: safeImageUrl("m15", "audio"),
    duration: "3:12",
    color: MEMORY_TYPE_COLOR.audio,
    source: "self",
    therapeuticTag: "daily_anchor",
  },
  {
    id: "m16",
    type: "video",
    date: "2020-09-03",
    title: "Reencuentro con la familia",
    tags: ["Familia"],
    location: { lat: -31.4, lng: -64.2, name: "Córdoba, AR" },
    lat: -31.42,
    lng: -64.19,
    imageUrl: safeImageUrl("m16", "video"),
    duration: "1:48",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "family_bond",
  },

  // ── SOCIALES ─────────────────────────────────────────────────────────────
  {
    id: "m17",
    type: "audio",
    date: "2021-06-10",
    title: "Conversación con mi abuela",
    tags: ["Familia", "Voz"],
    location: null,
    imageUrl: safeImageUrl("m17", "audio"),
    duration: "8:42",
    color: MEMORY_TYPE_COLOR.audio,
    source: "self",
    therapeuticTag: "family_bond",
  },
  {
    id: "m18",
    type: "video",
    date: "2021-11-30",
    title: "Cumpleaños sorpresa",
    tags: ["Celebración", "Amigos"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    lat: -34.60,
    lng: -58.38,
    imageUrl: safeImageUrl("m18", "video"),
    duration: "2:15",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "daily_anchor",
  },

  // ── CREATIVIDAD ──────────────────────────────────────────────────────────
  {
    id: "m19",
    type: "audio",
    date: "2023-05-14",
    title: "Una canción que escribí",
    tags: ["Música", "Creatividad"],
    location: null,
    imageUrl: safeImageUrl("m19", "audio"),
    duration: "3:48",
    color: MEMORY_TYPE_COLOR.audio,
    source: "self",
    therapeuticTag: "sensory",
  },
  {
    id: "m20",
    type: "video",
    date: "2022-08-19",
    title: "Concierto inolvidable",
    tags: ["Música"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    lat: -34.60,
    lng: -58.38,
    imageUrl: safeImageUrl("m20", "video"),
    duration: "0:58",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "sensory",
  },

  // ── CARRERA ──────────────────────────────────────────────────────────────
  {
    id: "m21",
    type: "video",
    date: "2023-09-01",
    title: "Primer día en el nuevo trabajo",
    tags: ["Carrera", "Trabajo"],
    location: { lat: -34.6, lng: -58.4, name: "Buenos Aires, AR" },
    lat: -34.60,
    lng: -58.38,
    imageUrl: safeImageUrl("m21", "video"),
    duration: "0:32",
    color: MEMORY_TYPE_COLOR.video,
    source: "self",
    therapeuticTag: "life_milestone",
  },
  {
    id: "m22",
    type: "note",
    date: "2023-09-09",
    title: "Una semana de aprendizajes",
    tags: ["Carrera", "Reflexión"],
    location: null,
    imageUrl: safeImageUrl("m22", "note"),
    description: "El cambio asusta, pero abre puertas que no sabías que existían.",
    color: MEMORY_TYPE_COLOR.note,
    source: "self",
    therapeuticTag: "daily_anchor",
  },

  // ── ALZHEIMER ESSENCE DONATIONS (Injected by family via MCP) ───────────
  {
    id: "m23",
    type: "photo",
    date: "1985-02-14",
    title: "Nuestra luna de miel en Mar del Plata",
    tags: ["Familia", "Amor", "Historia"],
    location: { lat: -38.0, lng: -57.5, name: "Mar del Plata, AR" },
    lat: -38.00,
    lng: -57.55,
    imageUrl: safeImageUrl("m23", "photo"),
    color: MEMORY_TYPE_COLOR.photo,
    description:
      "Teníamos 22 años. Nos escapamos en un tren viejo que tardó 10 horas. Hacía frío pero éramos felices.",
    source: "family",
    therapeuticTag: "identity", // Very important for reminiscence
    isFamilyDonation: true,
    donorName: "Marta",
    donorRelation: "Esposa",
    injectionNote: "Lauti, este recuerdo siempre lo hace sonreír cuando se siente perdido.",
    injectionStatus: "active",
  },
  {
    id: "m24",
    type: "audio",
    date: "1992-07-04",
    title: "Cuando nació Lautaro",
    tags: ["Familia", "Hitos"],
    location: { lat: -32.48, lng: -58.23, name: "Colón, Entre Ríos, AR" },
    lat: -32.22,
    lng: -58.15,
    imageUrl: safeImageUrl("m24", "audio"),
    color: MEMORY_TYPE_COLOR.audio,
    duration: "4:15",
    source: "family",
    therapeuticTag: "family_bond",
    isFamilyDonation: true,
    donorName: "Marta",
    donorRelation: "Esposa",
    injectionNote: "Grabación que hice con la videocámara el día que lo trajimos a casa.",
    injectionStatus: "active",
  }
]
